version: '3.8'
name: inception

services:
  nginx:
    image: nginx:42sp
    container_name: nginx
    build:
      context: requirements/nginx
    networks:
      - inception
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress

  wordpress:
    image: wordpress:42sp
    container_name: wordpress
    build:
      context: requirements/wordpress
    environment:
      - WP_DATABASE
      - WP_USER
      - WP_PASSWORD
    expose:
      - 9000
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:42sp
    container_name: mariadb
    build:
      context: requirements/mariadb
      args:
        - WP_DATABASE
        - WP_USER
        - WP_PASSWORD
    expose:
      - 3306
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql

  redis:
    image: redis:42sp
    container_name: redis
    build: requirements/bonus/redis
    expose:
      - 6379
    networks:
      - inception
    depends_on:
      - wordpress

networks:
  inception:
    name: inception

volumes:
  mariadb:
    driver_opts:
      o: bind
      type: none
      device: /home/marcelo/data/mariadb
  wordpress:
    driver_opts:
      o: bind
      type: none
      device: /home/marcelo/data/wordpress
