version: '3.8'
name: inception

services:
  nginx:
    image: nginx:42sp
    container_name: nginx
    build:
      context: requirements/nginx
      args:
        - LOGIN
    networks:
      - inception
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
      - website

  wordpress:
    image: wordpress:42sp
    container_name: wordpress
    build: requirements/wordpress
    environment:
       - DOMAIN
       - WP_TITLE
       - WP_ADMIN_USER
       - WP_ADMIN_PASS
       - WP_ADMIN_EMAIL
       - WP_DATABASE
       - WP_USER
       - WP_USER_PASS
       - WP_USER_EMAIL
    expose:
      - 9000
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
      - redis

  mariadb:
    image: mariadb:42sp
    container_name: mariadb
    build:
      context: requirements/mariadb
      args:
        - WP_DATABASE
        - WP_ADMIN_USER
        - WP_ADMIN_PASS
    expose:
      - 3306
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql

  redis:
    image: redis:42sp
    container_name: redis
    build: requirements/bonus/redis
    privileged: true
    expose:
      - 6379
    networks:
      - inception

  website:
    image: website:42sp
    container_name: website
    build: requirements/bonus/website
    expose:
      - 8080
    networks:
      - inception

  adminer:
    image: adminer:42sp
    container_name: adminer
    build: requirements/bonus/adminer
    networks:
      - inception
    expose:
      - 8081
    depends_on:
      - mariadb

  ftp:
    image: ftp:42sp
    container_name: ftp
    build:
      context: requirements/bonus/ftp
      args:
        - FTP_USER
        - FTP_PASS
    networks:
      - inception
    ports:
      - 20:20
      - 21:21
      - 42000-42005:42000-42005
    volumes:
      - wordpress:/home/vsftpd
    depends_on:
      - wordpress

  cadvisor:
    container_name: cadvisor
    build: requirements/bonus/cadvisor
    image: cadvisor:42sp
    ports:
      - 8080:8080
    networks:
      - inception
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    privileged: true
    devices:
      - /dev/kmsg

networks:
  inception:
    name: inception

volumes:
  mariadb:
    driver_opts:
      o: bind
      type: none
      device: /home/${LOGIN}/data/mariadb
  wordpress:
    driver_opts:
      o: bind
      type: none
      device: /home/${LOGIN}/data/wordpress
